image: Visual Studio 2017
configuration: Release
before_build:
  - nuget restore
build:
  parallel: true
  project: PGReliefMoreForGit.sln
test_script:
  - OpenCover.bat vstest.console.exe
  - .\packages\Codecov.1.0.3\tools\codecov.exe -f "coverage.xml"
