image: Visual Studio 2017
configuration: Release
before_build:
  - nuget restore
build:
  parallel: true
  project: PGReliefMoreForGit.sln
after_test:
  # OpenCover でカバレッジを計測
  - OpenCover.bat vstest.console.exe
  
  # Codecov への送信コマンド
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "result.xml"
