image: Visual Studio 2017
configuration: Release
before_build:
  - nuget restore
build:
  parallel: true
  project: PGReliefMoreForGit.sln
test_script:
  # OpenCover でカバレッジを計測
  - OpenCover.bat vstest.console.exe "coverage.xml"
  # Codecov へカバレッジ結果を渡す
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
